# Generated by Django 6.0.4 on 2026-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Автор')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Издательство')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Год')),
                ('genre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Жанр')),
                ('isbn_clean', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN (чистый)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
