# Generated by Django 6.0.4 on 2026-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_cartitem_remove_cart_unique_active_cart_per_customer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'is_active'), name='unique_active_cart_per_customer'),
        ),
    ]
